[env:mappi32]
extends = esp32_base
board = esp32dev
board_build.partitions = min_spiffs.csv
monitor_filters = esp32_exception_decoder

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32/mappi32

  ; Pin LoRa RFM95 Mappi32
  -D LORA_SCK=14
  -D LORA_MISO=12
  -D LORA_MOSI=13
  -D LORA_CS=15
  -D LORA_RST=0
  -D LORA_DIO0=27
  -D LORA_DIO1=-1
  -D LORA_DIO2=-1

  ; Nonaktifkan fitur yang tidak ada
  -D HAS_SCREEN=0
  -D HAS_GPS=0
  -D HAS_BATTERY=0
  -D HAS_TELEMETRY=0

lib_deps =
  ${esp32_base.lib_deps}